// @generated by protoc-gen-es v2.13.0 with parameter "target=ts,import_extension=js"
// @generated from file spell.proto (package proto, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { SpellSchool, Stat } from "./common_pb.js";
import { file_common } from "./common_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file spell.proto.
 */
export const file_spell: GenFile = /*@__PURE__*/
  fileDesc("CgtzcGVsbC5wcm90bxIFcHJvdG8iiQEKG1NjYWxpbmdJdGVtRWZmZWN0UHJvcGVydGllcxI8CgVzdGF0cxgBIAMoCzItLnByb3RvLlNjYWxpbmdJdGVtRWZmZWN0UHJvcGVydGllcy5TdGF0c0VudHJ5GiwKClN0YXRzRW50cnkSCwoDa2V5GAEgASgFEg0KBXZhbHVlGAIgASgBOgI4ASLuAwoKSXRlbUVmZmVjdBIPCgdidWZmX2lkGAEgASgFEhEKCWJ1ZmZfbmFtZRgGIAEoCRIaChJlZmZlY3RfZHVyYXRpb25fbXMYAiABKAUSHQoVbWF4X2N1bXVsYXRpdmVfc3RhY2tzGAcgASgFEj4KD3NjYWxpbmdfb3B0aW9ucxgDIAMoCzIlLnByb3RvLkl0ZW1FZmZlY3QuU2NhbGluZ09wdGlvbnNFbnRyeRIhCgRwcm9jGAQgASgLMhEucHJvdG8uUHJvY0VmZmVjdEgAEiQKBm9uX3VzZRgFIAEoCzISLnByb3RvLk9uVXNlRWZmZWN0SAASKAoNc3RhY2tpbmdfYXVyYRgIIAEoCzIRLnByb3RvLkl0ZW1FZmZlY3QSGQoPc3RhY2tfcGVyaW9kX21zGAkgASgFSAESJwoKc3RhY2tfcHJvYxgKIAEoCzIRLnByb3RvLlByb2NFZmZlY3RIARIUCgxzdGFja3NfZGVjYXkYCyABKAgaWQoTU2NhbGluZ09wdGlvbnNFbnRyeRILCgNrZXkYASABKAUSMQoFdmFsdWUYAiABKAsyIi5wcm90by5TY2FsaW5nSXRlbUVmZmVjdFByb3BlcnRpZXM6AjgBQggKBmVmZmVjdEIPCg1zdGFja190cmlnZ2VyIk4KClByb2NFZmZlY3QSDgoGaWNkX21zGAEgASgFEhUKC3Byb2NfY2hhbmNlGAIgASgBSAASDQoDcHBtGAMgASgBSABCCgoIcHJvY1JhdGUiVQoLT25Vc2VFZmZlY3QSEwoLY29vbGRvd25fbXMYASABKAUSEwoLY2F0ZWdvcnlfaWQYCyABKAUSHAoUY2F0ZWdvcnlfY29vbGRvd25fbXMYCCABKAUixwIKC1NwZWxsRWZmZWN0EgoKAmlkGAEgASgFEhAKCHNwZWxsX2lkGAIgASgFEg0KBWluZGV4GAMgASgFEh8KBHR5cGUYBCABKA4yES5wcm90by5FZmZlY3RUeXBlEhcKD21pbl9lZmZlY3Rfc2l6ZRgFIAEoARIVCg1lZmZlY3Rfc3ByZWFkGAYgASgBEiwKDXJlc291cmNlX3R5cGUYByABKA4yEy5wcm90by5SZXNvdXJjZVR5cGVIABIkCgZzY2hvb2wYCCABKA4yEi5wcm90by5TcGVsbFNjaG9vbEgAEhsKBHN0YXQYCSABKA4yCy5wcm90by5TdGF0SAASFgoOYXVyYV9wZXJpb2RfbXMYCiABKAUSDQoFc3RhdHMYCyADKAESEwoLZHVyYXRpb25fbXMYDCABKAVCDQoLbWlzY192YWx1ZTAqUwoKRWZmZWN0VHlwZRIVChFFZmZlY3RUeXBlVW5rbm93bhAAEhIKDkVmZmVjdFR5cGVIZWFsEAoSGgoWRWZmZWN0VHlwZVJlc291cmNlR2FpbhAeKtUBCgxSZXNvdXJjZVR5cGUSFAoQUmVzb3VyY2VUeXBlTm9uZRAAEhQKEFJlc291cmNlVHlwZU1hbmEQARIWChJSZXNvdXJjZVR5cGVFbmVyZ3kQAhIUChBSZXNvdXJjZVR5cGVSYWdlEAMSFQoRUmVzb3VyY2VUeXBlRm9jdXMQBBIbChdSZXNvdXJjZVR5cGVDb21ib1BvaW50cxAFEhYKElJlc291cmNlVHlwZUhlYWx0aBAGEh8KG1Jlc291cmNlVHlwZUdlbmVyaWNSZXNvdXJjZRAHQglaBy4vcHJvdG9iBnByb3RvMw", [file_common]);

/**
 * @generated from message proto.ScalingItemEffectProperties
 */
export type ScalingItemEffectProperties = Message<"proto.ScalingItemEffectProperties"> & {
  /**
   * keys are the numeric values of proto.common.Stat
   *
   * @generated from field: map<int32, double> stats = 1;
   */
  stats: { [key: number]: number };
};

/**
 * Describes the message proto.ScalingItemEffectProperties.
 * Use `create(ScalingItemEffectPropertiesSchema)` to create a new message.
 */
export const ScalingItemEffectPropertiesSchema: GenMessage<ScalingItemEffectProperties> = /*@__PURE__*/
  messageDesc(file_spell, 0);

/**
 * @generated from message proto.ItemEffect
 */
export type ItemEffect = Message<"proto.ItemEffect"> & {
  /**
   * @generated from field: int32 buff_id = 1;
   */
  buffId: number;

  /**
   * @generated from field: string buff_name = 6;
   */
  buffName: string;

  /**
   * milliseconds
   *
   * @generated from field: int32 effect_duration_ms = 2;
   */
  effectDurationMs: number;

  /**
   * @generated from field: int32 max_cumulative_stacks = 7;
   */
  maxCumulativeStacks: number;

  /**
   * Keyed to itemlevelstate
   *
   * @generated from field: map<int32, proto.ScalingItemEffectProperties> scaling_options = 3;
   */
  scalingOptions: { [key: number]: ScalingItemEffectProperties };

  /**
   * @generated from oneof proto.ItemEffect.effect
   */
  effect: {
    /**
     * @generated from field: proto.ProcEffect proc = 4;
     */
    value: ProcEffect;
    case: "proc";
  } | {
    /**
     * @generated from field: proto.OnUseEffect on_use = 5;
     */
    value: OnUseEffect;
    case: "onUse";
  } | { case: undefined; value?: undefined };

  /**
   * A second aura this effect accumulates rather than applies, set only when the stats live
   * there instead of in scaling_options above. Absent on the ordinary case.
   *
   * The aura named by buff_id lasts effect_duration_ms and grants nothing itself; it adds one
   * stack of this one at a time, up to its own max_cumulative_stacks, and its scaling_options
   * are the stats granted *per stack*. Gaining a stack does not refresh the window, which is
   * why the two cannot be flattened into a single stacking aura: that lets every stack restart
   * the duration and inflates both uptime and average stacks.
   *
   * @generated from field: proto.ItemEffect stacking_aura = 8;
   */
  stackingAura?: ItemEffect | undefined;

  /**
   * What makes the stacking aura gain a stack. Exactly one case is set whenever stacking_aura
   * is, and they are not interchangeable: a timer keeps stacking while the player does
   * nothing, an event does not.
   *
   * @generated from oneof proto.ItemEffect.stack_trigger
   */
  stackTrigger: {
    /**
     * A timer on the container aura: one stack every N milliseconds while the window is up.
     *
     * @generated from field: int32 stack_period_ms = 9;
     */
    value: number;
    case: "stackPeriodMs";
  } | {
    /**
     * An event: one stack per qualifying proc while the window is up.
     * Which procs qualify is derived from the container spell.
     *
     * @generated from field: proto.ProcEffect stack_proc = 10;
     */
    value: ProcEffect;
    case: "stackProc";
  } | { case: undefined; value?: undefined };

  /**
   * Set when the stacking aura starts at max_cumulative_stacks
   * and loses one per event rather than building up from zero.
   * Read from the tooltip, because the decrement is server script with no effect or flag behind it.
   *
   * @generated from field: bool stacks_decay = 11;
   */
  stacksDecay: boolean;
};

/**
 * Describes the message proto.ItemEffect.
 * Use `create(ItemEffectSchema)` to create a new message.
 */
export const ItemEffectSchema: GenMessage<ItemEffect> = /*@__PURE__*/
  messageDesc(file_spell, 1);

/**
 * @generated from message proto.ProcEffect
 */
export type ProcEffect = Message<"proto.ProcEffect"> & {
  /**
   * internal cooldown in milliseconds
   *
   * @generated from field: int32 icd_ms = 1;
   */
  icdMs: number;

  /**
   * @generated from oneof proto.ProcEffect.procRate
   */
  procRate: {
    /**
     * e.g. 0.20 = 20%
     *
     * @generated from field: double proc_chance = 2;
     */
    value: number;
    case: "procChance";
  } | {
    /**
     * @generated from field: double ppm = 3;
     */
    value: number;
    case: "ppm";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message proto.ProcEffect.
 * Use `create(ProcEffectSchema)` to create a new message.
 */
export const ProcEffectSchema: GenMessage<ProcEffect> = /*@__PURE__*/
  messageDesc(file_spell, 2);

/**
 * @generated from message proto.OnUseEffect
 */
export type OnUseEffect = Message<"proto.OnUseEffect"> & {
  /**
   * milliseconds between uses
   *
   * @generated from field: int32 cooldown_ms = 1;
   */
  cooldownMs: number;

  /**
   * @generated from field: int32 category_id = 11;
   */
  categoryId: number;

  /**
   * category cooldown in milliseconds
   *
   * @generated from field: int32 category_cooldown_ms = 8;
   */
  categoryCooldownMs: number;
};

/**
 * Describes the message proto.OnUseEffect.
 * Use `create(OnUseEffectSchema)` to create a new message.
 */
export const OnUseEffectSchema: GenMessage<OnUseEffect> = /*@__PURE__*/
  messageDesc(file_spell, 3);

/**
 * @generated from message proto.SpellEffect
 */
export type SpellEffect = Message<"proto.SpellEffect"> & {
  /**
   * @generated from field: int32 id = 1;
   */
  id: number;

  /**
   * @generated from field: int32 spell_id = 2;
   */
  spellId: number;

  /**
   * @generated from field: int32 index = 3;
   */
  index: number;

  /**
   * @generated from field: proto.EffectType type = 4;
   */
  type: EffectType;

  /**
   * @generated from field: double min_effect_size = 5;
   */
  minEffectSize: number;

  /**
   * @generated from field: double effect_spread = 6;
   */
  effectSpread: number;

  /**
   * @generated from oneof proto.SpellEffect.misc_value0
   */
  miscValue0: {
    /**
     * @generated from field: proto.ResourceType resource_type = 7;
     */
    value: ResourceType;
    case: "resourceType";
  } | {
    /**
     * @generated from field: proto.SpellSchool school = 8;
     */
    value: SpellSchool;
    case: "school";
  } | {
    /**
     * @generated from field: proto.Stat stat = 9;
     */
    value: Stat;
    case: "stat";
  } | { case: undefined; value?: undefined };

  /**
   * Milliseconds between periodic aura ticks; 0 for non-periodic effects
   *
   * @generated from field: int32 aura_period_ms = 10;
   */
  auraPeriodMs: number;

  /**
   * Stats the effect grants
   *
   * @generated from field: repeated double stats = 11;
   */
  stats: number[];

  /**
   * Duration of the effect's aura in milliseconds; 0 for instant effects
   *
   * @generated from field: int32 duration_ms = 12;
   */
  durationMs: number;
};

/**
 * Describes the message proto.SpellEffect.
 * Use `create(SpellEffectSchema)` to create a new message.
 */
export const SpellEffectSchema: GenMessage<SpellEffect> = /*@__PURE__*/
  messageDesc(file_spell, 4);

/**
 * @generated from enum proto.EffectType
 */
export enum EffectType {
  /**
   * @generated from enum value: EffectTypeUnknown = 0;
   */
  EffectTypeUnknown = 0,

  /**
   * @generated from enum value: EffectTypeHeal = 10;
   */
  EffectTypeHeal = 10,

  /**
   * @generated from enum value: EffectTypeResourceGain = 30;
   */
  EffectTypeResourceGain = 30,
}

/**
 * Describes the enum proto.EffectType.
 */
export const EffectTypeSchema: GenEnum<EffectType> = /*@__PURE__*/
  enumDesc(file_spell, 0);

/**
 * @generated from enum proto.ResourceType
 */
export enum ResourceType {
  /**
   * @generated from enum value: ResourceTypeNone = 0;
   */
  ResourceTypeNone = 0,

  /**
   * @generated from enum value: ResourceTypeMana = 1;
   */
  ResourceTypeMana = 1,

  /**
   * @generated from enum value: ResourceTypeEnergy = 2;
   */
  ResourceTypeEnergy = 2,

  /**
   * @generated from enum value: ResourceTypeRage = 3;
   */
  ResourceTypeRage = 3,

  /**
   * @generated from enum value: ResourceTypeFocus = 4;
   */
  ResourceTypeFocus = 4,

  /**
   * @generated from enum value: ResourceTypeComboPoints = 5;
   */
  ResourceTypeComboPoints = 5,

  /**
   * @generated from enum value: ResourceTypeHealth = 6;
   */
  ResourceTypeHealth = 6,

  /**
   * @generated from enum value: ResourceTypeGenericResource = 7;
   */
  ResourceTypeGenericResource = 7,
}

/**
 * Describes the enum proto.ResourceType.
 */
export const ResourceTypeSchema: GenEnum<ResourceType> = /*@__PURE__*/
  enumDesc(file_spell, 1);

