// @generated by protoc-gen-es v2.13.0 with parameter "target=ts,import_extension=js"
// @generated from file test.proto (package proto, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file test.proto.
 */
export const file_test: GenFile = /*@__PURE__*/
  fileDesc("Cgp0ZXN0LnByb3RvEgVwcm90byIvChhDaGFyYWN0ZXJTdGF0c1Rlc3RSZXN1bHQSEwoLZmluYWxfc3RhdHMYASADKAEiKAoVU3RhdFdlaWdodHNUZXN0UmVzdWx0Eg8KB3dlaWdodHMYASADKAEiUQoNRHBzVGVzdFJlc3VsdBILCgNkcHMYASABKAESCwoDdHBzGAIgASgBEgwKBGR0cHMYAyABKAESCwoDaHBzGAQgASgBEgsKA3RtaRgFIAEoASJxCg9DYXN0c1Rlc3RSZXN1bHQSMAoFY2FzdHMYASADKAsyIS5wcm90by5DYXN0c1Rlc3RSZXN1bHQuQ2FzdHNFbnRyeRosCgpDYXN0c0VudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoAToCOAEi/wQKD1Rlc3RTdWl0ZVJlc3VsdBJSChdjaGFyYWN0ZXJfc3RhdHNfcmVzdWx0cxgCIAMoCzIxLnByb3RvLlRlc3RTdWl0ZVJlc3VsdC5DaGFyYWN0ZXJTdGF0c1Jlc3VsdHNFbnRyeRJMChRzdGF0X3dlaWdodHNfcmVzdWx0cxgDIAMoCzIuLnByb3RvLlRlc3RTdWl0ZVJlc3VsdC5TdGF0V2VpZ2h0c1Jlc3VsdHNFbnRyeRI7CgtkcHNfcmVzdWx0cxgBIAMoCzImLnByb3RvLlRlc3RTdWl0ZVJlc3VsdC5EcHNSZXN1bHRzRW50cnkSPwoNY2FzdHNfcmVzdWx0cxgEIAMoCzIoLnByb3RvLlRlc3RTdWl0ZVJlc3VsdC5DYXN0c1Jlc3VsdHNFbnRyeRpdChpDaGFyYWN0ZXJTdGF0c1Jlc3VsdHNFbnRyeRILCgNrZXkYASABKAkSLgoFdmFsdWUYAiABKAsyHy5wcm90by5DaGFyYWN0ZXJTdGF0c1Rlc3RSZXN1bHQ6AjgBGlcKF1N0YXRXZWlnaHRzUmVzdWx0c0VudHJ5EgsKA2tleRgBIAEoCRIrCgV2YWx1ZRgCIAEoCzIcLnByb3RvLlN0YXRXZWlnaHRzVGVzdFJlc3VsdDoCOAEaRwoPRHBzUmVzdWx0c0VudHJ5EgsKA2tleRgBIAEoCRIjCgV2YWx1ZRgCIAEoCzIULnByb3RvLkRwc1Rlc3RSZXN1bHQ6AjgBGksKEUNhc3RzUmVzdWx0c0VudHJ5EgsKA2tleRgBIAEoCRIlCgV2YWx1ZRgCIAEoCzIWLnByb3RvLkNhc3RzVGVzdFJlc3VsdDoCOAFCCVoHLi9wcm90b2IGcHJvdG8z");

/**
 * @generated from message proto.CharacterStatsTestResult
 */
export type CharacterStatsTestResult = Message<"proto.CharacterStatsTestResult"> & {
  /**
   * @generated from field: repeated double final_stats = 1;
   */
  finalStats: number[];
};

/**
 * Describes the message proto.CharacterStatsTestResult.
 * Use `create(CharacterStatsTestResultSchema)` to create a new message.
 */
export const CharacterStatsTestResultSchema: GenMessage<CharacterStatsTestResult> = /*@__PURE__*/
  messageDesc(file_test, 0);

/**
 * @generated from message proto.StatWeightsTestResult
 */
export type StatWeightsTestResult = Message<"proto.StatWeightsTestResult"> & {
  /**
   * @generated from field: repeated double weights = 1;
   */
  weights: number[];
};

/**
 * Describes the message proto.StatWeightsTestResult.
 * Use `create(StatWeightsTestResultSchema)` to create a new message.
 */
export const StatWeightsTestResultSchema: GenMessage<StatWeightsTestResult> = /*@__PURE__*/
  messageDesc(file_test, 1);

/**
 * @generated from message proto.DpsTestResult
 */
export type DpsTestResult = Message<"proto.DpsTestResult"> & {
  /**
   * @generated from field: double dps = 1;
   */
  dps: number;

  /**
   * @generated from field: double tps = 2;
   */
  tps: number;

  /**
   * @generated from field: double dtps = 3;
   */
  dtps: number;

  /**
   * @generated from field: double hps = 4;
   */
  hps: number;

  /**
   * @generated from field: double tmi = 5;
   */
  tmi: number;
};

/**
 * Describes the message proto.DpsTestResult.
 * Use `create(DpsTestResultSchema)` to create a new message.
 */
export const DpsTestResultSchema: GenMessage<DpsTestResult> = /*@__PURE__*/
  messageDesc(file_test, 2);

/**
 * @generated from message proto.CastsTestResult
 */
export type CastsTestResult = Message<"proto.CastsTestResult"> & {
  /**
   * @generated from field: map<string, double> casts = 1;
   */
  casts: { [key: string]: number };
};

/**
 * Describes the message proto.CastsTestResult.
 * Use `create(CastsTestResultSchema)` to create a new message.
 */
export const CastsTestResultSchema: GenMessage<CastsTestResult> = /*@__PURE__*/
  messageDesc(file_test, 3);

/**
 * @generated from message proto.TestSuiteResult
 */
export type TestSuiteResult = Message<"proto.TestSuiteResult"> & {
  /**
   * Maps test names to their results.
   *
   * @generated from field: map<string, proto.CharacterStatsTestResult> character_stats_results = 2;
   */
  characterStatsResults: { [key: string]: CharacterStatsTestResult };

  /**
   * Maps test names to their results.
   *
   * @generated from field: map<string, proto.StatWeightsTestResult> stat_weights_results = 3;
   */
  statWeightsResults: { [key: string]: StatWeightsTestResult };

  /**
   * Maps test names to their results.
   *
   * @generated from field: map<string, proto.DpsTestResult> dps_results = 1;
   */
  dpsResults: { [key: string]: DpsTestResult };

  /**
   * @generated from field: map<string, proto.CastsTestResult> casts_results = 4;
   */
  castsResults: { [key: string]: CastsTestResult };
};

/**
 * Describes the message proto.TestSuiteResult.
 * Use `create(TestSuiteResultSchema)` to create a new message.
 */
export const TestSuiteResultSchema: GenMessage<TestSuiteResult> = /*@__PURE__*/
  messageDesc(file_test, 4);

