/**
 * data/enchants/index.json — the enchant side of the UI's applicability rule
 * (`enchantAppliesToItem`, ui/core/proto_utils/utils.ts upstream).
 *
 * Keyed by `effectId`, which is what WCL reports as `permanentEnchant` and
 * what `SimItemSpec.enchant` carries.
 *
 * Generated by scripts/generate_item_gem_index.py from vendor/wowsims/db.json
 * (gitignored build input, never read at runtime — PLAN.md §8.3 [P0]).
 * Re-run that script after `pnpm sync:wowsims` moves the pin.
 */

import rawEnchants from "../../../data/enchants/index.json" with { type: "json" };
import { getItem, type ItemEntry } from "./items.js";

/** common.proto EnchantType. Absent upstream means Normal. */
export const ENCHANT_TYPE_NORMAL = 0;
export const ENCHANT_TYPE_TWO_HAND = 1;
export const ENCHANT_TYPE_SHIELD = 2;
export const ENCHANT_TYPE_STAFF = 4;
export const ENCHANT_TYPE_OFF_HAND = 5;

/** common.proto WeaponType. */
const WEAPON_TYPE_OFF_HAND = 5;
const WEAPON_TYPE_SHIELD = 7;
const WEAPON_TYPE_STAFF = 8;

/** common.proto HandType. */
const HAND_TYPE_TWO_HAND = 4;

/** wowsims ItemType — the same enum `ItemEntry.itemType` carries. */
const ITEM_TYPE_RANGED = 14;

/** common.proto RangedWeaponType. */
const RANGED_WEAPON_TYPE_BOW = 2;
const RANGED_WEAPON_TYPE_CROSSBOW = 3;
const RANGED_WEAPON_TYPE_GUN = 4;
const RANGED_WEAPON_TYPE_WAND = 5;

export type EnchantEntry = {
  name: string | null;
  /** Slot this enchant applies to, in the same enum as `ItemEntry.itemType`. */
  type: number | null;
  enchantType: number;
};

const INDEX = rawEnchants as Record<string, EnchantEntry>;

export function getEnchant(effectId: number): EnchantEntry | undefined {
  return INDEX[String(effectId)];
}

/**
 * Port of the UI's `enchantAppliesToItem`.
 *
 * `isEnchantable` only answers "does this slot take an enchant at all", so it
 * happily carries a 2H-only enchant onto a one-hander. This answers the
 * narrower question the UI asks before keeping an enchant across a swap
 * (`EquippedItem.withItem`).
 *
 * The shield / staff / off-hand branches cannot fire for a ret paladin — the
 * universe admits two-handers and librams only — but they are kept so the
 * rule matches upstream rather than encoding our current pool as an
 * invariant.
 */
export function enchantAppliesToItem(
  effectId: number,
  itemId: number
): boolean {
  const enchant = getEnchant(effectId);
  const item = getItem(itemId);
  if (!enchant || !item) return false;

  // Slot intersection. Upstream compares expanded ItemSlot lists; ours is a
  // single slot per side, both drawn from the same wowsims ItemType enum.
  if (enchant.type == null || enchant.type !== item.itemType) return false;

  if (
    enchant.enchantType === ENCHANT_TYPE_TWO_HAND &&
    item.handType !== HAND_TYPE_TWO_HAND
  ) {
    return false;
  }

  if (
    enchant.enchantType === ENCHANT_TYPE_STAFF &&
    item.weaponType !== WEAPON_TYPE_STAFF
  ) {
    return false;
  }

  if (
    enchant.enchantType === ENCHANT_TYPE_SHIELD &&
    item.weaponType !== WEAPON_TYPE_SHIELD
  ) {
    return false;
  }

  // An off-hand enchant belongs on an off-hand or shield and nowhere else,
  // and conversely a non-off-hand enchant must not land on one — upstream
  // writes this as an inequality between the two predicates.
  const isOffHandEnchant = enchant.enchantType === ENCHANT_TYPE_OFF_HAND;
  const takesOffHandEnchant =
    item.weaponType === WEAPON_TYPE_OFF_HAND ||
    (item.weaponType === WEAPON_TYPE_SHIELD &&
      enchant.enchantType !== ENCHANT_TYPE_SHIELD);
  if (isOffHandEnchant !== takesOffHandEnchant) return false;

  if (enchant.type === ITEM_TYPE_RANGED) {
    const shootable =
      item.rangedWeaponType === RANGED_WEAPON_TYPE_BOW ||
      item.rangedWeaponType === RANGED_WEAPON_TYPE_CROSSBOW ||
      item.rangedWeaponType === RANGED_WEAPON_TYPE_GUN;
    if (!shootable) return false;
  }

  // A libram/idol/totem (ranged slot, non-wand) takes no non-ranged enchant.
  if (
    item.rangedWeaponType != null &&
    item.rangedWeaponType !== RANGED_WEAPON_TYPE_WAND &&
    item.rangedWeaponType > 0 &&
    enchant.type !== ITEM_TYPE_RANGED
  ) {
    return false;
  }

  return true;
}

export type { ItemEntry };
