/**
 * data/enchants/index.json — the enchant side of the UI's applicability rule
 * (`enchantAppliesToItem`, ui/core/proto_utils/utils.ts upstream).
 *
 * Keyed by `effectId`, which is what WCL reports as `permanentEnchant` and
 * what `SimItemSpec.enchant` carries.
 *
 * Generated by scripts/generate_item_gem_index.py from vendor/wowsims/db.json
 * (gitignored build input, never read at runtime — PLAN.md §8.3 [S0]).
 * Re-run that script after `pnpm sync:wowsims` moves the pin.
 */

import rawEnchants from "../../../data/enchants/index.json" with { type: "json" };
import { getItem, type ItemEntry } from "./items.js";
import {
  EnchantType,
  HandType,
  ItemType,
  RangedWeaponType,
  WeaponType,
} from "./proto/common_pb.js";

/**
 * A hand-copied copy of RangedWeaponType had drifted one value up, denying
 * bows a scope and granting one to thrown weapons (carry-forward 83). CI
 * regenerates these enums and byte-compares them against the committed output
 * (`.github/workflows/verify.yml`, `pnpm proto:generate` then `git diff
 * --exit-code`), which `pnpm verify` does not do — that step is the gate, not
 * the generate command on its own.
 */

export type EnchantEntry = {
  name: string | null;
  /** Slot this enchant applies to, in the same enum as `ItemEntry.itemType`. */
  type: number | null;
  enchantType: number;
  /**
   * Further slots the same enchant also applies to. Armor kits carry it —
   * Heavy Knothide is `type: 1` with `extraTypes: [3, 5, 7, 9, 10]` — and
   * upstream's rule unions the two rather than testing `type` alone.
   */
  extraTypes: number[];
};

/**
 * `effectId` is not unique: 141 records share 137 ids. Each entry is the list
 * of records for that id, disambiguated against the item's own slot.
 */
const INDEX = rawEnchants as Record<string, EnchantEntry[]>;

export function getEnchants(effectId: number): EnchantEntry[] {
  return INDEX[String(effectId)] ?? [];
}

/** Every slot this enchant applies to, `type` unioned with `extraTypes`. */
function eligibleSlots(enchant: EnchantEntry): number[] {
  return enchant.type == null
    ? [...enchant.extraTypes]
    : [enchant.type, ...enchant.extraTypes];
}

/**
 * The record for `effectId` that fits `itemType`, or undefined.
 *
 * With a colliding id the slot is what tells the two apart — 2564 is both
 * Gloves - Superior Agility and Weapon - Agility, and only one of those can
 * be the enchant on a given item.
 */
export function getEnchant(
  effectId: number,
  itemType?: number
): EnchantEntry | undefined {
  const records = getEnchants(effectId);
  if (itemType === undefined) return records[0];
  return records.find((e) => eligibleSlots(e).includes(itemType));
}

/**
 * Port of the UI's `enchantAppliesToItem`.
 *
 * `isEnchantable` only answers "does this slot take an enchant at all", so it
 * happily carries a 2H-only enchant onto a one-hander. This answers the
 * narrower question the UI asks before keeping an enchant across a swap
 * (`EquippedItem.withItem`).
 *
 * The shield / staff / off-hand branches cannot fire for a ret paladin — the
 * universe admits two-handers and librams only — but they are kept so the
 * rule matches upstream rather than encoding our current pool as an
 * invariant.
 */
export function enchantAppliesToItem(
  effectId: number,
  itemId: number
): boolean {
  const item = getItem(itemId);
  if (!item) return false;

  // Slot intersection, and the reason getEnchant needs the item's slot: an
  // effectId can name two enchants for different slots, and only the one
  // matching this item can be the enchant it carries. Upstream unions
  // `type` with `extraTypes` here (getEligibleEnchantSlots) -- armor kits
  // are `type: 1` with `extraTypes: [3, 5, 7, 9, 10]`, so testing `type`
  // alone would strip a Knothide kit off every non-head slot it sits on.
  const enchant = getEnchant(effectId, item.itemType);
  if (!enchant) return false;

  if (
    enchant.enchantType === EnchantType.EnchantTypeTwoHand &&
    item.handType !== HandType.HandTypeTwoHand
  ) {
    return false;
  }

  if (
    enchant.enchantType === EnchantType.EnchantTypeStaff &&
    item.weaponType !== WeaponType.WeaponTypeStaff
  ) {
    return false;
  }

  if (
    enchant.enchantType === EnchantType.EnchantTypeShield &&
    item.weaponType !== WeaponType.WeaponTypeShield
  ) {
    return false;
  }

  // An off-hand enchant belongs on an off-hand or shield and nowhere else,
  // and conversely a non-off-hand enchant must not land on one — upstream
  // writes this as an inequality between the two predicates.
  const isOffHandEnchant =
    enchant.enchantType === EnchantType.EnchantTypeOffHand;
  const takesOffHandEnchant =
    item.weaponType === WeaponType.WeaponTypeOffHand ||
    (item.weaponType === WeaponType.WeaponTypeShield &&
      enchant.enchantType !== EnchantType.EnchantTypeShield);
  if (isOffHandEnchant !== takesOffHandEnchant) return false;

  if (enchant.type === ItemType.ItemTypeRanged) {
    const shootable =
      item.rangedWeaponType === RangedWeaponType.RangedWeaponTypeBow ||
      item.rangedWeaponType === RangedWeaponType.RangedWeaponTypeCrossbow ||
      item.rangedWeaponType === RangedWeaponType.RangedWeaponTypeGun;
    if (!shootable) return false;
  }

  // A libram/idol/totem (ranged slot, non-wand) takes no non-ranged enchant.
  if (
    item.rangedWeaponType != null &&
    item.rangedWeaponType !== RangedWeaponType.RangedWeaponTypeWand &&
    item.rangedWeaponType > 0 &&
    enchant.type !== ItemType.ItemTypeRanged
  ) {
    return false;
  }

  return true;
}

export type { ItemEntry };
