/**
 * data/enchants/index.json — the enchant side of the UI's applicability rule
 * (`enchantAppliesToItem`, ui/core/proto_utils/utils.ts upstream).
 *
 * Keyed by `effectId`, which is what WCL reports as `permanentEnchant` and
 * what `SimItemSpec.enchant` carries.
 *
 * Generated by scripts/generate_item_gem_index.py from vendor/wowsims/db.json
 * (gitignored build input, never read at runtime — PLAN.md §8.3 [P0]).
 * Re-run that script after `pnpm sync:wowsims` moves the pin.
 */

import rawEnchants from "../../../data/enchants/index.json" with { type: "json" };
import { getItem, type ItemEntry } from "./items.js";
import {
  EnchantType,
  HandType,
  ItemType,
  RangedWeaponType,
  WeaponType,
} from "./proto/common_pb.js";

/**
 * These came from the proto rather than being re-typed here: a hand-copied
 * copy of RangedWeaponType had drifted one value up, denying bows a scope and
 * granting one to thrown weapons (carry-forward 83). `pnpm proto:generate`
 * regenerates the imported enums from data/proto, so the next upstream change
 * cannot silently disagree with them.
 */

/** Absent upstream means Normal. */
export const ENCHANT_TYPE_NORMAL = EnchantType.EnchantTypeNormal;
export const ENCHANT_TYPE_TWO_HAND = EnchantType.EnchantTypeTwoHand;
export const ENCHANT_TYPE_SHIELD = EnchantType.EnchantTypeShield;
export const ENCHANT_TYPE_STAFF = EnchantType.EnchantTypeStaff;
export const ENCHANT_TYPE_OFF_HAND = EnchantType.EnchantTypeOffHand;

const WEAPON_TYPE_OFF_HAND = WeaponType.WeaponTypeOffHand;
const WEAPON_TYPE_SHIELD = WeaponType.WeaponTypeShield;
const WEAPON_TYPE_STAFF = WeaponType.WeaponTypeStaff;

const HAND_TYPE_TWO_HAND = HandType.HandTypeTwoHand;

/** The same enum `ItemEntry.itemType` carries. */
const ITEM_TYPE_RANGED = ItemType.ItemTypeRanged;

const RANGED_WEAPON_TYPE_BOW = RangedWeaponType.RangedWeaponTypeBow;
const RANGED_WEAPON_TYPE_CROSSBOW = RangedWeaponType.RangedWeaponTypeCrossbow;
const RANGED_WEAPON_TYPE_GUN = RangedWeaponType.RangedWeaponTypeGun;
const RANGED_WEAPON_TYPE_WAND = RangedWeaponType.RangedWeaponTypeWand;

export type EnchantEntry = {
  name: string | null;
  /** Slot this enchant applies to, in the same enum as `ItemEntry.itemType`. */
  type: number | null;
  enchantType: number;
  /**
   * Further slots the same enchant also applies to. Armor kits carry it —
   * Heavy Knothide is `type: 1` with `extraTypes: [3, 5, 7, 9, 10]` — and
   * upstream's rule unions the two rather than testing `type` alone.
   */
  extraTypes: number[];
};

/**
 * `effectId` is not unique: 141 records share 137 ids. Each entry is the list
 * of records for that id, disambiguated against the item's own slot.
 */
const INDEX = rawEnchants as Record<string, EnchantEntry[]>;

export function getEnchants(effectId: number): EnchantEntry[] {
  return INDEX[String(effectId)] ?? [];
}

/** Every slot this enchant applies to, `type` unioned with `extraTypes`. */
function eligibleSlots(enchant: EnchantEntry): number[] {
  return enchant.type == null
    ? [...enchant.extraTypes]
    : [enchant.type, ...enchant.extraTypes];
}

/**
 * The record for `effectId` that fits `itemType`, or undefined.
 *
 * With a colliding id the slot is what tells the two apart — 2564 is both
 * Gloves - Superior Agility and Weapon - Agility, and only one of those can
 * be the enchant on a given item.
 */
export function getEnchant(
  effectId: number,
  itemType?: number
): EnchantEntry | undefined {
  const records = getEnchants(effectId);
  if (itemType === undefined) return records[0];
  return records.find((e) => eligibleSlots(e).includes(itemType));
}

/**
 * Port of the UI's `enchantAppliesToItem`.
 *
 * `isEnchantable` only answers "does this slot take an enchant at all", so it
 * happily carries a 2H-only enchant onto a one-hander. This answers the
 * narrower question the UI asks before keeping an enchant across a swap
 * (`EquippedItem.withItem`).
 *
 * The shield / staff / off-hand branches cannot fire for a ret paladin — the
 * universe admits two-handers and librams only — but they are kept so the
 * rule matches upstream rather than encoding our current pool as an
 * invariant.
 */
export function enchantAppliesToItem(
  effectId: number,
  itemId: number
): boolean {
  const item = getItem(itemId);
  if (!item) return false;

  // Slot intersection, and the reason getEnchant needs the item's slot: an
  // effectId can name two enchants for different slots, and only the one
  // matching this item can be the enchant it carries. Upstream unions
  // `type` with `extraTypes` here (getEligibleEnchantSlots) -- armor kits
  // are `type: 1` with `extraTypes: [3, 5, 7, 9, 10]`, so testing `type`
  // alone would strip a Knothide kit off every non-head slot it sits on.
  const enchant = getEnchant(effectId, item.itemType);
  if (!enchant) return false;

  if (
    enchant.enchantType === ENCHANT_TYPE_TWO_HAND &&
    item.handType !== HAND_TYPE_TWO_HAND
  ) {
    return false;
  }

  if (
    enchant.enchantType === ENCHANT_TYPE_STAFF &&
    item.weaponType !== WEAPON_TYPE_STAFF
  ) {
    return false;
  }

  if (
    enchant.enchantType === ENCHANT_TYPE_SHIELD &&
    item.weaponType !== WEAPON_TYPE_SHIELD
  ) {
    return false;
  }

  // An off-hand enchant belongs on an off-hand or shield and nowhere else,
  // and conversely a non-off-hand enchant must not land on one — upstream
  // writes this as an inequality between the two predicates.
  const isOffHandEnchant = enchant.enchantType === ENCHANT_TYPE_OFF_HAND;
  const takesOffHandEnchant =
    item.weaponType === WEAPON_TYPE_OFF_HAND ||
    (item.weaponType === WEAPON_TYPE_SHIELD &&
      enchant.enchantType !== ENCHANT_TYPE_SHIELD);
  if (isOffHandEnchant !== takesOffHandEnchant) return false;

  if (enchant.type === ITEM_TYPE_RANGED) {
    const shootable =
      item.rangedWeaponType === RANGED_WEAPON_TYPE_BOW ||
      item.rangedWeaponType === RANGED_WEAPON_TYPE_CROSSBOW ||
      item.rangedWeaponType === RANGED_WEAPON_TYPE_GUN;
    if (!shootable) return false;
  }

  // A libram/idol/totem (ranged slot, non-wand) takes no non-ranged enchant.
  if (
    item.rangedWeaponType != null &&
    item.rangedWeaponType !== RANGED_WEAPON_TYPE_WAND &&
    item.rangedWeaponType > 0 &&
    enchant.type !== ITEM_TYPE_RANGED
  ) {
    return false;
  }

  return true;
}

export type { ItemEntry };
