/**
 * data/gems/palette.json (PLAN.md §5.1, §9 R4) — every gem the meta-repair
 * solver may consider, JC-restricted gems already excluded at generation
 * time (professions aren't modelled; a JC-only recommendation is a dead end
 * for anyone else — §9). `phase` and `unique` are kept per-entry rather than
 * filtered here, same "filtering happens at rank time" pattern as
 * data/pools/<spec>.json (§8.3), so a maxPhase change doesn't need a
 * regeneration.
 *
 * Generated by scripts/generate_item_gem_index.py from vendor/wowsims/db.json.
 */

import rawPalette from "../../../data/gems/palette.json" with { type: "json" };
import { GemColor } from "./proto/common_pb.js";

export type GemColour = number;

export type GemEntry = {
  id: number;
  colour: GemColour;
  /** Raw stat-index array, same shape as db.json's gems[].stats. */
  stats: number[];
  phase: number;
  /** Unique gems are excluded from multi-socket consideration (§9 R4.2). */
  unique: boolean;
};

const PALETTE = rawPalette as GemEntry[];

export function gemPalette(): readonly GemEntry[] {
  return PALETTE;
}

export function getGem(gemId: number): GemEntry | undefined {
  return PALETTE.find((g) => g.id === gemId);
}

export function gemsForPhase(maxPhase: number): GemEntry[] {
  return PALETTE.filter((g) => g.phase <= maxPhase);
}

/**
 * The meta gem among `gemIds`, if any. A character can only have one, so the
 * first match wins.
 *
 * Lives here rather than in the ranking orchestrator: deciding what counts as
 * a meta gem is a fact about gem data, not about how a swap is scored.
 */
export function findMetaGemId(gemIds: readonly number[]): number | undefined {
  for (const id of gemIds) {
    if (getGem(id)?.colour === GemColor.GemColorMeta) return id;
  }
  return undefined;
}
