/**
 * data/gems/palette.json (PLAN.md §5.1, §9 R4) — every gem the meta-repair
 * solver may consider, JC-restricted gems already excluded at generation
 * time (professions aren't modelled; a JC-only recommendation is a dead end
 * for anyone else — §9). `phase` and `unique` are kept per-entry rather than
 * filtered here, same "filtering happens at rank time" pattern as
 * data/pools/<spec>.json (§8.3), so a maxPhase change doesn't need a
 * regeneration.
 *
 * Generated by scripts/generate_item_gem_index.py from vendor/wowsims/db.json.
 */

import rawPalette from "../../../data/gems/palette.json" with { type: "json" };
import { GemColor } from "./proto/common_pb.js";

export type GemColour = number;

export type GemEntry = {
  id: number;
  colour: GemColour;
  /** Raw stat-index array, same shape as db.json's gems[].stats. */
  stats: number[];
  phase: number;
  /** db.json item quality: 2 uncommon, 3 rare, 4 epic (ticket 111). */
  quality: number;
  /** Unique gems are excluded from multi-socket consideration (§9 R4.2). */
  unique: boolean;
};

const PALETTE = rawPalette as GemEntry[];

export function gemPalette(): readonly GemEntry[] {
  return PALETTE;
}

export function getGem(gemId: number): GemEntry | undefined {
  return PALETTE.find((g) => g.id === gemId);
}

export function gemsForPhase(maxPhase: number): GemEntry[] {
  return PALETTE.filter((g) => g.phase <= maxPhase);
}

/**
 * Like gemsForPhase, what counts as an available gem is a fact about gem
 * data, so the quality filter lives here rather than at the call site
 * (ticket 111, revised by ticket 117 — both the auto-fill path and meta
 * repair now cap rarity, via `GemContext.fillPalette`).
 *
 * `null`/`undefined` `quality` used to take opposite paths: `null <= 3` is
 * `true` in JS (the entry silently passed the cap), `undefined <= 3` is
 * `false` (the entry silently dropped). Neither was reported, so a caller
 * building its own palette (tests, or any future direct constructor) had no
 * signal either way (ticket 114). A committed `data/gems/palette.json` entry
 * always carries a number — the generator guarantees it — so this only fires
 * on a malformed injected palette, and it fires loudly: a safety net that
 * fabricates a verdict on missing data is worse than no net.
 */
export function gemsForQuality(
  palette: readonly GemEntry[],
  maxQuality: number
): GemEntry[] {
  return palette.filter((g) => {
    if (typeof g.quality !== "number") {
      throw new Error(
        `gem ${g.id} has non-numeric quality (${String(g.quality)}); cannot apply the rarity cap`
      );
    }
    return g.quality <= maxQuality;
  });
}

/**
 * Auto-fill and meta repair both cap at rare (owner decision, ticket 111,
 * extended to repair by ticket 117): a player's own epics ride through
 * migration, but neither path assumes epics they may not own.
 *
 * The cap used to be call-site discipline — `candidate-gems.ts` held its own
 * `MAX_FILL_QUALITY` constant and remembered to pass it to `gemsForQuality`
 * on every palette it built. Two palettes existed on one `GemContext`
 * (`palette` uncapped, `fillPalette` capped), type-indistinguishable from
 * each other, so grabbing the wrong one compiled fine and only showed up as
 * an epic gem nobody asked for (tickets 117/116, both since fixed at their
 * call sites — this is the chokepoint that keeps the bug class from
 * recurring at a new one). Moving the cap in here means there is exactly one
 * way to get a fill-eligible palette, and it cannot be constructed by
 * forgetting a filter call. Fixed default for now; a run-level option
 * mirroring wowsims' rarity/phase dropdowns is future work.
 */
export const FILL_MAX_QUALITY = 3;

export function fillEligibleGems(
  palette: readonly GemEntry[]
): readonly GemEntry[] {
  return gemsForQuality(palette, FILL_MAX_QUALITY);
}

/**
 * The meta gem among `gemIds`, if any. A character can only have one, so the
 * first match wins.
 *
 * Lives here rather than in the ranking orchestrator: deciding what counts as
 * a meta gem is a fact about gem data, not about how a swap is scored.
 */
export function findMetaGemId(gemIds: readonly number[]): number | undefined {
  for (const id of gemIds) {
    if (getGem(id)?.colour === GemColor.GemColorMeta) return id;
  }
  return undefined;
}
