/**
 * data/items/index.json (PLAN.md §5.1, §9) — every equippable item, not just
 * the candidate pool. Load-bearing for gear the player is *already wearing*:
 * normalize must ask "can this slot carry an enchant / does it have sockets"
 * before synthesizing anything, or it invents enchants for rings/gems for
 * socketless items and reports them as substitutions (§9).
 *
 * Generated by scripts/generate_item_gem_index.py from vendor/wowsims/db.json
 * (gitignored build input, never read at runtime — PLAN.md §8.3 [P0]).
 * Re-run that script after `pnpm sync:wowsims` moves the pin.
 */

import rawIndex from "../../../data/items/index.json" with { type: "json" };

export type ItemSlot =
  | "head"
  | "neck"
  | "shoulder"
  | "back"
  | "chest"
  | "wrist"
  | "hands"
  | "waist"
  | "legs"
  | "feet"
  | "finger"
  | "trinket"
  | "weapon"
  | "ranged";

export type ItemEntry = {
  name: string;
  slot: ItemSlot;
  /** Socket colours, one entry per socket. Empty when the item has none. */
  sockets: number[];
  /** Stat array granted only when every socket is colour-matched (§9 R4). */
  socketBonus: number[];
  /**
   * Whether TBC allows a permanent enchant on this slot at all — not
   * whether *this specific* item currently has one. Neck/waist/trinket are
   * the three slots with zero enchant recipes in wowsims' db.json; finger
   * (rings) are enchantable via the Enchanting profession's "Enchant Ring -
   * *" recipes, confirmed against real WCL fixture data
   * (test/fixtures/slamaltman.raw.json shows 14/50 ring slots enchanted).
   *
   * Not sufficient to gate synthesis on its own. Ring enchants are
   * enchanter-only (the only four records in db.json's enchants[] with a
   * requiredProfession), so `enchantable: true` on a finger does not mean
   * this player can apply one. Synthesis must additionally gate on observed
   * per-slot presence, or a synthesized candidate enchant gets compared
   * against a bare baseline slot and its stats are misattributed to the
   * item — PLAN.md §9, "the symmetry invariant".
   */
  enchantable: boolean;
  setId: number | null;
  phase: number;
  unique: boolean;
  /** Numeric profession id if this item requires one to use, else null. */
  requiredProfession: number | null;
};

// The generated file is keyed by item id as a string (JSON object keys are
// always strings); re-typed here so callers don't have to know that.
const INDEX = rawIndex as Record<string, ItemEntry>;

export function getItem(itemId: number): ItemEntry | undefined {
  return INDEX[String(itemId)];
}

export function isEnchantable(itemId: number): boolean {
  return getItem(itemId)?.enchantable ?? false;
}

export function socketsFor(itemId: number): number[] {
  return getItem(itemId)?.sockets ?? [];
}
