// GENERATED by scripts/generate_json_literal_types.py -- do not edit.
// Source: packages/core/src/item-source-kinds.json (kinds)
//
// Hand-editing this file will be reverted by `pnpm codegen:json-types`, and
// `pnpm verify` fails while it is out of step with the JSON.

/**
 * Discriminants of the `ItemSource` union in `pool.ts`.
 * `assemble_universe.py` validates every emitted source against the
 * same JSON and refuses the build on an unknown kind, so this list
 * crossing the language boundary intact is a correctness property.
 *
 * `as const` is the whole point: the JSON import this replaces widened
 * to `string[]`, so a union derived from it accepted any string.
 */
export const ITEM_SOURCE_KINDS = [
  "raid",
  "token",
  "badge",
  "crafted",
  "rep",
  "heroic",
  "pvp",
  "world",
] as const;

export type ItemSourceKindName = (typeof ITEM_SOURCE_KINDS)[number];
