// GENERATED by scripts/generate_json_literal_types.py -- do not edit.
// Source: packages/core/src/slots-table.json (simOrder)
//
// Hand-editing this file will be reverted by `pnpm codegen:json-types`, and
// `pnpm verify` fails while it is out of step with the JSON.

/**
 * The 17 sim equipment slots, in order.
 * `scripts/slots.py` reads the same JSON for the 19->17 mapping.
 *
 * `as const` is the whole point: the JSON import this replaces widened
 * to `string[]`, so a union derived from it accepted any string.
 */
export const SIM_ORDER = [
  "head",
  "neck",
  "shoulder",
  "back",
  "chest",
  "wrist",
  "hands",
  "waist",
  "legs",
  "feet",
  "finger1",
  "finger2",
  "trinket1",
  "trinket2",
  "mainhand",
  "offhand",
  "ranged",
] as const;

export type SimOrderName = (typeof SIM_ORDER)[number];
