// GENERATED by scripts/generate_json_literal_types.py -- do not edit.
// Source: packages/core/src/spec-registry.json (specs)
//
// Hand-editing this file will be reverted by `pnpm codegen:json-types`, and
// `pnpm verify` fails while it is out of step with the JSON.

/**
 * Every spec this engine can rank.
 * The ids are the keys of `spec-registry.json`, which also carries
 * each spec's fork proto name for `assemble_universe.py`. Adding an
 * id here without completing its `SPEC_REGISTRY` entry in
 * `spec-registry.ts` is a compile error, which is the point: every
 * per-spec field is a game fact with no safe default.
 *
 * `as const` is the whole point: the JSON import this replaces widened
 * to `string[]`, so a union derived from it accepted any string.
 */
export const SPEC_IDS = [
  "balance",
  "feral",
  "hunter",
  "mage",
  "ret",
  "shadow",
  "rogue",
  "ele",
  "enh",
  "warlock",
  "warrior",
] as const;

export type SpecId = (typeof SPEC_IDS)[number];
