#!/usr/bin/env python3
"""
build_feral_skeleton.py — generate the feral cat RaidSimRequest skeleton.

Ret's skeleton came from a wowsims share link via `wowsimcli decodelink`
(PLAN.md §8.2, design C). No feral share link exists here, so this builds the
equivalent from sources that ARE pinned:

  - encounter block: copied from the ret skeleton. It describes the FIGHT
    rather than the player, and upstream defines it per-spec identically
    (feral's sim.ts encounterPicker carries no duration override), so there
    is nothing spec-specific to lose.
  - buff/debuff/individual-buff blocks: feral's OWN upstream defaults, read
    from data/presets/feral/buff-defaults.json (generated by
    scripts/extract_sim_defaults.mjs straight out of upstream's sim.ts).
    These used to be copied from ret; ADR 0022 records why that was wrong.
  - player class, talents, options, consumables, race, professions: from
    upstream ui/druid/feralcat/presets.ts at the pinned commit.
  - rotation: merged from the pinned vendor/wowsims/feral_default.apl.json.

The APL merge is not cosmetic. verification-log 2026-07-27 measured that for
ret the APL block -- prepullActions especially -- is what the Go sim actually
runs, and that `type`+`simple` alone produces a different, wrong DPS. So the
feral skeleton carries the same four APL fields.

Before that copy happens, the APL JSON is checked against apl_schema.py's
extraction of data/proto/*.proto (issue #1, step 8): the pinned wowsimcli
binary (v0.0.101) unmarshals with DiscardUnknown: true, so a field name our
proto pin doesn't know about is silently dropped rather than erroring --
upstream's newer feral APL uses `timeToNextEnergyTick`, which produces a
plausible but wrong rotation under that pin with no signal at all. This
script refuses to write a skeleton containing a field name absent from the
pinned schema; re-pin the proto (fetch:protos) before regenerating past that
point.

    python scripts/build_feral_skeleton.py

Exit 0 ok, 1 unknown APL field, 2 missing inputs.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from apl_schema import known_fields, unknown_field_keys  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
RET_SKELETON = ROOT / "data/presets/ret/p2.raid-sim-skeleton.json"
FERAL_APL = ROOT / "vendor/wowsims/feral_default.apl.json"
OUT = ROOT / "data/presets/feral/p2.raid-sim-skeleton.json"

APL_KEYS = ("prepullActions", "priorityList", "groups", "valueVariables")

# ui/druid/feralcat/presets.ts @ 8aa378b3. StandardTalents rather than
# MonocatTalents: it is the preset upstream lists first and the one its P2
# gear sets are built around.
TALENTS = "-503032132322105301251-05503301"

# OtherDefaults in the same file.
RACE = "RaceNightElf"
PROFESSION1 = "Engineering"
PROFESSION2 = "Enchanting"
REACTION_TIME_MS = 250
DISTANCE_FROM_TARGET = 0

# DefaultConsumables in the same file. The `potions`/`conjuredItems` menu
# arrays ret carries are deliberately omitted: check_raid_sim_skeleton.py's
# docstring records them as exported UI menus with an unknown filter, inert
# for ret, so inventing feral values would be fabrication rather than a port.
CONSUMABLES = {
    "potId": 22838,
    "battleElixirId": 22831,
    "guardianElixirId": 32067,
    "foodId": 27664,
    "mhImbueId": 34340,
    "conjuredId": 12662,
    "drumsId": "GreaterDrumsOfBattle",
    "superSapper": True,
    "goblinSapper": True,
    "scrollAgi": True,
    "scrollStr": True,
}

# Buffs, debuffs and party buffs come from data/presets/feral/buff-defaults.json,
# extracted from upstream's own sim.ts by scripts/extract_sim_defaults.mjs
# (ADR-0022). Not inlined here: they are upstream's values, and a constant in
# this file would go stale silently on a tag bump. `pnpm sim-defaults:check`
# gates the generated file against the pinned source.
#
# Two upstream quirks the extractor carries through faithfully, worth knowing
# when reading the output:
#   - feral spreads defaultExposeWeaknessSettings(Phase.Phase1) with an EXPLICIT
#     Phase1, so exposeWeaknessHunterAgility is 1080 even though this is a P2
#     tool (utils.ts phase map: Phase1 1080, Phase2 1150). Mirroring upstream is
#     the point — "correcting" it to 1150 would re-diverge from the browser.
#   - partyBuffs.drums and CONSUMABLES.drumsId are different proto fields, not a
#     duplicate: common.proto:479 is what someone ELSE in the party plays,
#     common.proto:593 is what this player plays. Upstream sets both.
BUFF_DEFAULTS = ROOT / "data/presets/feral/buff-defaults.json"


def main() -> int:
    for path in (RET_SKELETON, FERAL_APL, BUFF_DEFAULTS):
        if not path.is_file():
            print(f"missing {path.relative_to(ROOT)}", file=sys.stderr)
            if path is FERAL_APL:
                print("  run: pnpm sync:wowsims:restore", file=sys.stderr)
            if path is BUFF_DEFAULTS:
                print("  run: pnpm sim-defaults:build", file=sys.stderr)
            return 2

    skeleton = json.loads(RET_SKELETON.read_text(encoding="utf-8"))
    apl = json.loads(FERAL_APL.read_text(encoding="utf-8"))
    buffs = json.loads(BUFF_DEFAULTS.read_text(encoding="utf-8"))

    # DiscardUnknown: true means the pinned binary drops a field it doesn't
    # recognise instead of erroring -- so check before the copy, not after.
    # Only the four fields this script actually carries forward (APL_KEYS)
    # matter here; unrelated top-level keys in the vendor APL file (if any)
    # are never read.
    apl_subset = {key: apl.get(key) for key in APL_KEYS}
    unknown = unknown_field_keys(apl_subset, known_fields())
    if unknown:
        print(
            f"{FERAL_APL} uses field(s) unknown to the pinned "
            f"proto (data/proto/*.proto): {unknown}",
            file=sys.stderr,
        )
        print(
            "  the pinned wowsimcli binary silently discards unrecognised fields "
            "(DiscardUnknown: true) rather than erroring -- writing this skeleton "
            "would produce a plausible but wrong rotation with no signal.",
            file=sys.stderr,
        )
        print("  re-pin the proto (pnpm fetch:protos) before regenerating.", file=sys.stderr)
        return 1

    raid = skeleton["raid"]
    party = raid["parties"][0]
    player = party["players"][0]

    # Assigned, never merged: a merge would leave ret-only keys (thorns,
    # curseOfElements, jocRetribution2pt4, leaderOfThePack) alive in a feral
    # request, which is the exact bug ADR 0022 is about.
    raid["buffs"] = buffs["raidBuffs"]
    raid["debuffs"] = buffs["debuffs"]
    party["buffs"] = buffs["partyBuffs"]
    player["buffs"] = buffs["individualBuffs"]

    player["name"] = "feral"
    player["class"] = "ClassDruid"
    player["talentsString"] = TALENTS
    player["race"] = RACE
    player["profession1"] = PROFESSION1
    player["profession2"] = PROFESSION2
    player["reactionTimeMs"] = REACTION_TIME_MS
    player["distanceFromTarget"] = DISTANCE_FROM_TARGET
    player["consumables"] = CONSUMABLES

    # The spec-options oneof: exactly one of these may be set.
    player.pop("retributionPaladin", None)
    player["feralCatDruid"] = {"options": {"classOptions": {}}}

    # Rotation: the APL is what the Go sim runs (verification-log 2026-07-27).
    rotation = {"type": "TypeAPL"}
    for key in APL_KEYS:
        rotation[key] = apl.get(key)
    player["rotation"] = rotation

    # Gear is filled per-candidate by compose; ship the skeleton bare so a
    # stale ret item can never leak into a feral request.
    player["equipment"] = {"items": [{} for _ in range(17)]}

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(skeleton, indent=2) + "\n", encoding="utf-8")

    print(f"wrote {OUT.relative_to(ROOT)}")
    print(f"  class={player['class']} race={player['race']}")
    print(f"  talents={player['talentsString']}")
    print(f"  rotation.type={rotation['type']}, "
          f"prepullActions={len(rotation.get('prepullActions') or [])}, "
          f"priorityList={len(rotation.get('priorityList') or [])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
