#!/usr/bin/env python3
"""
Emit `as const` TypeScript for JSON string lists that TypeScript needs as types.

    python scripts/generate_json_literal_types.py            # write
    python scripts/generate_json_literal_types.py --check    # fail if stale

Why this exists
---------------
A JSON import always widens to `string[]`. `import k from "./k.json"` gives
`k.kinds: string[]`, never a literal union, and `as const` cannot rescue it --
TS1355, "const assertions can only be applied to ... literals", because a JSON
import is not a literal.

That makes every type-level guard against a JSON import a lie that type-checks:

    type Kind = (typeof k.kinds)[number];   // = string
    const bad: Kind = "not-a-kind";         // compiles clean

The repo hit this twice. Once deriving `SimSlotName` from `SIM_ORDER`, where
the conclusion recorded was "impossible, needs codegen" (ticket 24); once
pinning `item-source-kinds.json` against the `ItemSource` union, where an
assertion in one direction passed vacuously (ticket 28 follow-up). Both times
the assertion looked rigorous and proved nothing.

So the JSON stays the *value* source of truth -- Python reads it, and it is
what ships -- and this script derives the *type* from it. Generated output is
committed and gated by `--check` in `pnpm verify`, the same contract
`fetch:protos:check` and `mirrors:check` already use.

Exit 0 ok, 1 stale (--check), 2 missing input.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "packages" / "core" / "src"

# source JSON -> (key holding the string list, generated .ts, exported names)
TARGETS = [
    {
        "json": SRC / "item-source-kinds.json",
        "key": "kinds",
        "out": SRC / "item-source-kinds.generated.ts",
        "const": "ITEM_SOURCE_KINDS",
        "type": "ItemSourceKindName",
        "doc": (
            "Discriminants of the `ItemSource` union in `pool.ts`.\n"
            " * `assemble_universe.py` validates every emitted source against the\n"
            " * same JSON and refuses the build on an unknown kind, so this list\n"
            " * crossing the language boundary intact is a correctness property."
        ),
    },
    {
        "json": SRC / "slots-table.json",
        "key": "simOrder",
        "out": SRC / "slots-sim-order.generated.ts",
        "const": "SIM_ORDER",
        "type": "SimOrderName",
        "doc": (
            "The 17 sim equipment slots, in order.\n"
            " * `scripts/slots.py` reads the same JSON for the 19->17 mapping."
        ),
    },
    {
        "json": SRC / "slots-table.json",
        "key": "wclOrder",
        "out": SRC / "slots-wcl-order.generated.ts",
        "const": "WCL_ORDER",
        "type": "WclOrderName",
        "doc": "The 19 WCL gear slots, in order, before shirt/tabard are dropped.",
    },
]

HEADER = """// GENERATED by scripts/generate_json_literal_types.py -- do not edit.
// Source: {src} ({key})
//
// Hand-editing this file will be reverted by `pnpm codegen:json-types`, and
// `pnpm verify` fails while it is out of step with the JSON.
"""


def render(target: dict, values: list[str]) -> str:
    src_rel = target["json"].relative_to(ROOT).as_posix()
    lines = [HEADER.format(src=src_rel, key=target["key"]).rstrip("\n")]
    lines.append("")
    lines.append("/**")
    lines.append(f" * {target['doc']}")
    lines.append(" *")
    lines.append(
        " * `as const` is the whole point: the JSON import this replaces widened"
    )
    lines.append(" * to `string[]`, so a union derived from it accepted any string.")
    lines.append(" */")
    lines.append(f"export const {target['const']} = [")
    for v in values:
        lines.append(f"  {json.dumps(v)},")
    lines.append("] as const;")
    lines.append("")
    lines.append(
        f"export type {target['type']} = (typeof {target['const']})[number];"
    )
    lines.append("")
    return "\n".join(lines)


def prettify(text: str, out: Path) -> str:
    """
    Run the repo's Prettier over the rendered text.

    Without this the generator and `format:check` disagree forever: the
    generator writes one layout, Prettier rewrites it, and `--check` then
    reports the file as stale on the next run. Formatting here means the
    committed bytes are what both steps expect. `--stdin-filepath` is what
    makes Prettier apply the .ts rules and the repo's config.
    """
    # On Windows `shutil.which("npx")` finds the extensionless shell script,
    # which CreateProcess cannot execute (WinError 193). Prefer the .cmd.
    npx = (
        shutil.which("npx.cmd") if sys.platform == "win32" else None
    ) or shutil.which("npx")
    if npx is None:
        # Better a readable failure than silently committing unformatted output
        # that CI will reject.
        print("npx not found — cannot format generated output", file=sys.stderr)
        raise SystemExit(2)
    done = subprocess.run(
        [npx, "prettier", "--stdin-filepath", str(out)],
        input=text,
        capture_output=True,
        text=True,
        cwd=ROOT,
    )
    if done.returncode != 0:
        print(done.stderr.strip(), file=sys.stderr)
        raise SystemExit(2)
    return done.stdout


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if any file is stale")
    args = ap.parse_args()

    stale: list[str] = []
    for target in TARGETS:
        if not target["json"].is_file():
            print(f"missing {target['json'].relative_to(ROOT)}", file=sys.stderr)
            return 2
        doc = json.loads(target["json"].read_text(encoding="utf-8"))
        values = doc.get(target["key"])
        if not isinstance(values, list) or not all(isinstance(v, str) for v in values):
            print(
                f"{target['json'].relative_to(ROOT)}: {target['key']!r} is not a "
                "list of strings",
                file=sys.stderr,
            )
            return 2
        if len(set(values)) != len(values):
            dupes = sorted({v for v in values if values.count(v) > 1})
            print(
                f"{target['json'].relative_to(ROOT)}: {target['key']!r} has "
                f"duplicates {dupes} -- a literal union would silently collapse them",
                file=sys.stderr,
            )
            return 2

        out = target["out"]
        want = prettify(render(target, values), out)
        have = out.read_text(encoding="utf-8") if out.is_file() else None
        rel = out.relative_to(ROOT).as_posix()
        if have == want:
            continue
        if args.check:
            stale.append(rel)
        else:
            out.write_text(want, encoding="utf-8")
            print(f"wrote {rel}")

    if args.check:
        if stale:
            print("generated types are stale:", file=sys.stderr)
            for rel in stale:
                print(f"  {rel}", file=sys.stderr)
            print(
                "run `pnpm codegen:json-types` and commit the result",
                file=sys.stderr,
            )
            return 1
        print("generated JSON literal types are in sync.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
